### PR TITLE
Merging arm-intake into dev

### PR DESCRIPTION
**Pull request by BrandonBeaver117**
Getting the arm and intake subsystems into the dev branch

### CODE REVIEW

**Comment by a-viv-a** [comment]
You need to format the code before it can be merged

**Comment by BrandonBeaver117** [comment]
Spotless has been satisfied! 🎉

**Comment by a-viv-a** [comment]
i forgot about this and now its in conflict with dev bc i updated spotless independently--sorry. Mind resolving the conflict?

**Comment by BrandonBeaver117** [comment]
np, but iirc, didn't you want me to not merge this? Something about how the other feat branches are just taking from this one anyway?

**Comment by a-viv-a** [comment]
Yeah I guess I'm unclear how to handle this, will think about it more.

**Comment by a-viv-a** [comment]
The features from this pr have been moved to betabot branches, closing.

**Pull request closed without merging**
